name: ranked_list
description: A tiny library allows you to create ranked list view.
version: 0.0.1
author: Dheeraj Bhavsar
homepage: https://github.com/BhavsarDheeraj/ranked_list

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: